export const BUNDLE_VERSION = 'BUNDLE_VERSION';

export const BUNDLE_URL = 'BUNDLE_URL';

export const DEFAULT_TRAINING_STAMINA = 'DEFAULT_TRAINING_STAMINA';

export const CURRRENT_SEASON = 'CURRRENT_SEASON';

export const CURRRENT_ROUND = 'CURRRENT_ROUND';

export const NEXT_ROUND = 'NEXT_ROUND';
